### ISSUE TITLE
should.js in document example has HTMLElements dependency

### ISSUE THREAD

**Issue by Sophrinix** [tonylukasavage/ti-mocha#13] opened 2014-01-27 12:53 UTC
[I created a repository](https://github.com/CodexLabs/AlloyTiMochaExample) which eliminates enough of the HTML/DOM dependencies on should.js to allow someone to just copy should into a project the way you are [proposing in the documentation ](http://tonylukasavage.com/ti-mocha/).

If you literally follow your instructions a common message you will run into is:

undefined variable HTMLElement

lines 227-243 are problematic for 
https://github.com/visionmedia/should.js/blob/master/should.js.

It turns out deleting those lines works for titanium's purposes. 
I suppose if you wanted to later on unit test content inside a webview, you might get burnt, but iI'll cross that bridge when I need to.

**Comment by tonylukasavage** [comment] 2014-01-27 13:16
I have not found that to be the case. I used should.js exactly as indicated in the documentation for all the samples and my own testing as well, including the ticket I resolved in Alloy ([ALOY-920](https://jira.appcelerator.org/browse/ALOY-920)). Can you provide some specifics about your test setup? 
- What reporter are you using? You're using one with a `ti-` prefix right? 
- What does your test suite look like? Perhaps you are using sections of mocha that I have not reached with my testing. 
- Can you narrow it down to a specific test that is causing the issue? Perhaps a particular call from should.js that you're using it causing the issue.

**Comment by Sophrinix** [comment] 2014-01-27 19:05
I'ved tried 
   mocha.setup({ reporter: 'ti-spec' });

in both index.js and in the test file before the describe block.

**Comment by tonylukasavage** [comment] 2014-01-27 19:08
Please copy over the info in #14 that is relevant to this ticket so we can continue the conversation. Also, can you please list the smallest possible script that shows this error? The full contents of the JS file please since I can't reproduce this on my own.

**Comment by Sophrinix** [comment] 2014-01-27 19:20
**SCENARIO 1**
[start with my repo](https://github.com/CodexLabs/AlloyTiMochaExample)
1) delete should.js from app/lib/

2) ➜ npm install ti-mocha && npm install should
unbuild should@3.1.0
should@3.1.0 node_modules/should 

3) ➜ com.codexlabs.com.alloytimocha git:(master) ✗ npm ls
/Users/andrewmcelroy/repos/com.codexlabs.com.alloytimocha
├── should@3.1.0
└── ti-mocha@0.1.1

this should technically work.

**SCENARIO 2**
[start with my repo](https://github.com/CodexLabs/AlloyTiMochaExample)
1) delete should.js from app/lib/

2) ➜ com.codexlabs.com.alloytimocha git:(master) ✗ npm install ti-mocha

3) ✗ npm ls
/Users/andrewmcelroy/repos/com.codexlabs.com.alloytimocha
└── ti-mocha@0.1.1

4) curl https://raw.github.com/visionmedia/should.js/master/should.js > /Users/andrewmcelroy/repos/com.codexlabs.com.alloytimocha/app/lib/should.js 

5) ti build --platform ios
....
com.alloytimocha.app/should.js:1\n#6 () at file:///Users/andrewmcelroy/Library/Application%20Support/iPhone%20Simulator/7.0/Applications/440353AC-1369-4415-9B4A-FF48D5151F3C/com.codexlabs.com.alloytimocha.app/should.js:2319";
[ERROR]     line = 228;
[ERROR]     message = "Can't find variable: HTMLElement";

---

The only way I can make this work is if I delete the lines previously mentioned.

**Comment by tonylukasavage** [comment] 2014-01-27 19:27
### Scenario 1

This should not technically work and failing would be expected if you did this. As I mentioned in the [docs](http://tonylukasavage.com/ti-mocha/#using-shouldjs-with-ti-mocha), you need to copy should.js in manually. Titanium doesn't currently support a node.js-like `require()` so there's no way this will work until it does. So throw that case right out.

### Scenario 2

Can you please provide the full JS you are using to run the test since I can't reproduce it on my own? Also, if possible, please use the un-minified version of should.js and give me the full stack trace of the error. I see the problem you are citing, but I never encounter it in my usage.

**Comment by tonylukasavage** [comment] 2014-01-27 19:29
Nevermind, found this: [https://github.com/visionmedia/should.js/commit/33331c92834106846196a1bf1c59ee032990ab81](https://github.com/visionmedia/should.js/commit/33331c92834106846196a1bf1c59ee032990ab81)

They changed the check for that element recently, which is what is causing the break for you. Might need to log a PR.

**Comment by Sophrinix** [comment] 2014-01-27 19:37
https://github.com/visionmedia/should.js/commit/33331c92834106846196a1bf1c59ee032990ab81#commitcomment-5190636
In the meantime I'll just write it up as a blog post. 

The other issue can be closed. Technically, this issue can be closed too. The GH Page should be updated to point this out.

**Comment by tonylukasavage** [comment] 2014-01-27 19:37
I'm leaving it open, working on a PR to resolve the issue in should.js now

**Comment by tonylukasavage** [comment] 2014-01-27 20:33
[https://github.com/visionmedia/should.js/pull/173](https://github.com/visionmedia/should.js/pull/173) merged. All fixed now.

**Closed as completed by tonylukasavage** 2014-01-27 20:33 UTC
